version: "3.1"

services:
  node-20:
    image: node:20

  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 90:5055
      - 5174:5172
      - 6006:6006
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - postgres

  db:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    # volumes:
    #   - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin:

  # db:
  #   image: mysql:lts
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: your_root_password
  #     MYSQL_DATABASE: your_database_name
  #     MYSQL_USER: your_username
  #     MYSQL_PASSWORD: your_password
  #   # volumes:
  #   #   - /my/own/datadir:/var/lib/mysql

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: always
  #   ports:
  #     - "8080:80"
  #   environment:
  #     PMA_HOST: db
  #     MYSQL_ROOT_PASSWORD: your_root_password
