version: "3.1"

services:
  node-20:
    image: node:20

  app:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: app
    build:
      context: ./app
      dockerfile: ../Dockerfile.prod
    ports:
      - 90:5055
    tty: true
    stdin_open: true
    restart: on-failure
    networks:
      - postgres
    depends_on:
      db:
        condition: service_healthy
        restart: true

  db:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    # volumes:
    #   - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
